# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK_Test_API' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.5'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'Kingfisher', '~> 6.0.1'

  # Pods for VK_Test_API

end
